import Footer from '../components/Footer'
import '../globals.css'
import Provider from './Provider'


export const metadata = {
  title: 'Kasim portfolio site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative min-h-screen'>
        <Provider>
        {children}
        <Footer/>
        </Provider>
         {/* Footer */}
        </body>
    </html>
  )
}
